services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: emoni-lorawan:latest
    container_name: emoni-lorawan
    restart: unless-stopped
    environment:
      - PORT=8000
      - DB_PATH=/app/data/data.db
      - CHIRPSTACK_WEBHOOK_TOKEN=${CHIRPSTACK_WEBHOOK_TOKEN:-}
      - UI_TIMEZONE=${UI_TIMEZONE:-Europe/Berlin}
      - UI_DAYS=${UI_DAYS:-30}
    volumes:
      - emoni_data:/app/data

  caddy:
    image: caddy:2
    container_name: emoni-caddy
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  emoni_data:
  caddy_data:
  caddy_config:
