services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: emoni-lorawan:latest
    container_name: emoni-lorawan
    restart: unless-stopped
    environment:
      - PORT=8000
      - DB_PATH=/app/data/data.db
      - CHIRPSTACK_WEBHOOK_TOKEN=${CHIRPSTACK_WEBHOOK_TOKEN:-}
      - UI_TIMEZONE=${UI_TIMEZONE:-Europe/Berlin}
      - UI_DAYS=${UI_DAYS:-30}
    volumes:
      - emoni_data:/app/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: emoni-cloudflared
    restart: unless-stopped
    depends_on:
      - app
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}

volumes:
  emoni_data:
