services:
  caddy:
    image: caddy:2
    container_name: emoni-edge-caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile.edge:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
