services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: emoni-lorawan:latest
    container_name: emoni-lorawan
    restart: unless-stopped
    environment:
      - PORT=8000
      - DB_PATH=/app/data/data.db
      - CHIRPSTACK_WEBHOOK_TOKEN=${CHIRPSTACK_WEBHOOK_TOKEN:-}
      - UI_TIMEZONE=${UI_TIMEZONE:-Europe/Berlin}
      - UI_DAYS=${UI_DAYS:-30}
    volumes:
      - emoni_data:/app/data

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: emoni-tunnel
    restart: unless-stopped
    depends_on:
      - app
    command: tunnel --config /etc/cloudflared/config.yaml run
    volumes:
      - ./cloudflared.yaml:/etc/cloudflared/config.yaml:ro
      - ./cloudflared-credentials.json:/etc/cloudflared/credentials.json:ro

volumes:
  emoni_data:
